### ISSUE TITLE
39: Wärmeerzeugung: Integration eines Erzeugerlastgangs ermöglichen

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/Sophena#19]
**Fragen**
* [x] Haben die Auswahl des Produktbereichs und der Produktgruppe noch eine andere Funktion als die Kosten zu initialisieren und beim BHWK auf Stromerzeugung zu schließen? Wenn nicht, braucht man diese nicht zu speichern.
* [x] Zumindest das Festlegen der Brennstoffgruppe beim Anlegen eines Erzeugerlastgangs könnte hilfreich sein -> da sich die Felder bei der Brennstoffauswahl für Holz und andere Brennstoffe unterscheiden.

> Eventuell kann man die Brennstoffgruppe direkt an die Produktgruppe hängen -> dies würde beide Fragen klären

**TODO**
* [x] Erzeugerlastgänge habe immer Grundlast als Defaultwert für die Funktion
* [x] Brennstoffauswahl -> Kostenrechnung
* [x] Wenn KWK-Anlagen ausgewählt wurden, dann braucht man noch das Feld für die
  `elektrische Nennleistung`; diese muss dann für Erzeugerprofile analog wie bei den anderen
  Erzeugern in die Berechnung für den erzeugten Strom eingehen
* [x] Außerdem braucht man noch das Feld für die maximale thermische Leistung. Dieses sollte
  editierbar sein und mit dem maximalen Wert aus dem Lastgang initialisiert werden
* [x] Beide Felder sollten am besten direkt unter das Erzeugerprofil gesetzt werden
* ~~Stromgeführtes BHKW~~ nach #82 verschoben

**Comment by wscarmen** [comment]
Bei Erzeugerlastgängen macht die Angabe einer Wärmerückgewinnung keinen Sinn. Dieser Bereich soll also bei Erzeugerlastgängen wegfallen.

**Comment by wscarmen** [comment]
- Bei den Farben gibt es noch Überschneidungen, die Logik der Farbzuweisung erschließt sich mir nicht ...
- Das Feld "Maximale thermische Leistung" soll aus dem initialen Dialogfenster herausgenommen werden
- In der Graphik wäre es evtl. schön, wenn nur das abgreifbare Leistungsband dargestellt wird (d.h. pro Stunde der Bereich zwischen minimaler und maximaler Leistung)

**Comment by msrocka** [comment]
Wenn man den gelben Bereich einfach weiß färbt, wird die Logik vielleicht klar, denn das ist dann genau das Leistungsband wie in Punkt 3 beschrieben:

![image](https://user-images.githubusercontent.com/3520062/48545420-2bc06d80-e8c6-11e8-8fb2-f995088444a5.png)

**Comment by wscarmen** [comment]
- [ ] Bei einem BHKW-Lastgang wird die erzeugte Strommenge bei den Konversionverlusten immer noch nicht berücksichtigt
- [ ] Wenn bei einem Lastgang max. und minimale Leistung identisch sind, wird keine Linie angezeigt, sondern gar nichts ...

**Comment by msrocka** [comment]
Punkt zwei müsste jetzt gelöst sein:
![image](https://user-images.githubusercontent.com/3520062/48902836-1618ee00-ee5a-11e8-9d6f-d27c9fcad172.png)

**zu Punkt 1:**

Im Konzept steht dazu:
>  Die Konversionsverluste ergeben sich aus der Multiplikation der benötigten Brennstoffmengen eines Wärmeerzeugers mit dem jeweiligen Wert für (1-Nutzungsgrad). Bei KWK-Anlagen ergibt sich der Nutzungsgrad für diese Berechnungen aus der Summe des thermischen und elektrischen Wirkungsgrads.

Nun haben wir aber für die Erzeugerprofile keinen thermischen Wirkungsgrad (sondern nur den Nutzungsgrad als manuelle Eingabe). Soll dieser dann aus dem Nutzungsgrad zurückgerechnet werden?

Ich habe schon ein Feld für den elektrischen Wirkungsgrad von Erzeugerprofilen hinzugefügt, aber das mit dem fehlenden thermischen  Wirkungsgrad ist mir jetzt erst aufgefallen.

![image](https://user-images.githubusercontent.com/3520062/48903194-2087b780-ee5b-11e8-8225-d753cafea5e6.png)

**Zu Punkt 3:**

Ich habe versucht das zu lösen, aber das ist leider etwas aufwändiger.

**Comment by wscarmen** [comment]
- Bei KWK-Anlagen gehen wir davon aus, dass der thermische Nutzungsgrad dem thermischen Wirkungsgrad entspricht. 
- Aus der thermischen Leistung P_th und dem thermischen Wirkungsgrad W_th kann die Feuerungswärmeleistung FWL berechnet werden: FWL = P_th/W_th
- Aus der Feuerungswärmeleistung FWL und der elektrischen Leistung P_el kann der elektrische Wirkungsgrad W_el berechnet werden: W_el = P_el/FWL
- Gesamtformel ist also: W_el = P_el/(P_th/W_th)

**Comment by wscarmen** [comment]
Der Punkt "Bei einem BHKW-Lastgang wird die erzeugte Strommenge bei den Konversionverlusten nicht berücksichtigt" ist immer noch nicht umgesetzt.

**Comment by msrocka** [comment]
Mir ist nicht ganz klar, was hier falsch ist. In dem Konzept steht:

> Die Konversionsverluste ergeben sich aus der Multiplikation der benötigten
  Brennstoffmengen eines Wärmeerzeugers mit dem jeweiligen Wert für
  (1-Nutzungsgrad). Bei KWK-Anlagen ergibt sich der Nutzungsgrad für diese
  Berechnungen aus der Summe des thermischen und elektrischen Wirkungsgrads.

Bei dem Lastgang im Beispiel handelt es sich um eine KWK-Anlage. Der angegebene
Nutzungsgrad im Lastgang ist `0.5`. Laut Definition oben ist das auch der
thermische Wirkungsgrad. Mit der Formel oben ergibt sich der folgende
elektrische Wirkungsgrad:

```julia
W_el = (P_el / P_th) * W_th = (150 / 200 ) * 0.5 = 0.375
```

Bei einem Brennstoffbedarf von `1.306.000 kWh` ergeben sich die folgenden
Konversionsverluste:

```julia
C = (1 - (0.375 + 0.5)) * 1306000 = 163250.0  # kWh ; => 12 % 
```

Und das ist das, was Sophena hier anzeigt:

![image](https://user-images.githubusercontent.com/3520062/53034543-a7a4f580-3473-11e9-8379-f1e44035fb96.png)
